import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'

import Button from 'ui/button/button.component';
import { BUTTON_TYPE_CLASSES } from 'ui/button/button.component';

import Card from 'ui/card/card.component';
import { CardSize } from 'ui/card/card.styled';

const Title = styled.h1`
  color: red;
`;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button isLoading={false} buttonType={BUTTON_TYPE_CLASSES.squared}>
        test
      </Button>

      <Card imgUrl="/hero-sm.png" size={CardSize.big}/>

      <p>hello</p>
      <Title>Testing</Title>
    </>
  )
}

export default Home
